#!/usr/bin/perl

# By: Justin Lee
# Date: QUANRANTINE 2020
#
# Description:
#   Yo dawg, this is an RPN calculator.
#   It does that kind of thing, you
#   know?


use strict;

# init the RPN calculator
RPN->prime;

# parse the input
foreach my $input (@ARGV)
{
	my @command = ();

	# if we're given files stack their input onto the queue
	if (-f $input)
	{
		if (open(my $fh, q[<], $input))
		{
			while (<$fh>)
			{
				chomp;
				s/^\s+//;
				s/\s+$//;
				s/#.*//;
				next unless length;

				push @command, $_;
			}
		}
		else
		{
			warn qq[Skipping file '$input': $!];
			next; # skipperoo
		}
	}
	else
	{
		$command[0] = $input;
	}

	# parse commands
	foreach my $command (@command)
	{
		RPN::execute($command);
	}
}


exit 0;



################
# SUB PACKAGES #
################ objectify me, daddi


  ######
  #   RPN
   #    The main calculation interface and CPU
   #    control interface, etc.

package RPN;

use strict;

sub FALSE() { 0 }
sub TRUE()  { 1 }

sub bool2num(_)  { shift() ? TRUE : FALSE }
sub force2num(_) { 0 + shift }

my $stack;
my $command;
my $register;
my %operation;
my %help;

sub prime
{
	RPN::Register->prime; # get er' nice and ready
	$register = RPN::Register->init; # control unit
	$stack = $register->frame->top; # calculator stack is always top frame

	%operation =
	(
		# tests
		'=='  => sub { if ($stack->has(2)) { $stack->push(($stack->get(1) == $stack->get(2)) ? TRUE : FALSE) } },
		'!='  => sub { if ($stack->has(2)) { $stack->push(($stack->get(1) == $stack->get(2)) ? FALSE : TRUE) } }, # lol
		'<'   => sub { if ($stack->has(2)) { $stack->push(($stack->get(1)  < $stack->get(2)) ? TRUE : FALSE) } },
		'>'   => sub { if ($stack->has(2)) { $stack->push(($stack->get(1)  > $stack->get(2)) ? TRUE : FALSE) } },
		'<='  => sub { if ($stack->has(2)) { $stack->push(($stack->get(1) <= $stack->get(2)) ? TRUE : FALSE) } },
		'>='  => sub { if ($stack->has(2)) { $stack->push(($stack->get(1) >= $stack->get(2)) ? TRUE : FALSE) } },
		# ternary ops
		'?'   => sub { if ($stack->has(3)) { if ($stack->pop) { my $k = $stack->pop; $stack->set(1, $k) } else { $stack->pop } } },
		# binary ops
		'+'   => sub { if ($stack->has(2)) { $stack->push($stack->pop +  $stack->pop) } }, 
		'/'   => sub { if ($stack->has(2)) { $stack->push($stack->pop /  $stack->pop) } },
		'*'   => sub { if ($stack->has(2)) { $stack->push($stack->pop *  $stack->pop) } },
		'-'   => sub { if ($stack->has(2)) { $stack->push($stack->pop -  $stack->pop) } },
		'%'   => sub { if ($stack->has(2)) { $stack->push($stack->pop %  $stack->pop) } },
		'**'  => sub { if ($stack->has(2)) { $stack->push($stack->pop ** $stack->pop) } },
		'^'   => sub { if ($stack->has(2)) { $stack->push($stack->pop ^  $stack->pop) } },
		'&'   => sub { if ($stack->has(2)) { $stack->push($stack->pop &  $stack->pop) } },
		'|'   => sub { if ($stack->has(2)) { $stack->push($stack->pop |  $stack->pop) } },
		'<<'  => sub { if ($stack->has(2)) { $stack->push($stack->pop << $stack->pop) } },
		'>>'  => sub { if ($stack->has(2)) { $stack->push($stack->pop >> $stack->pop) } }, # vvv safe boolean ops
		'&&'  => sub { if ($stack->has(2)) { my ($a,$b) = ($stack->pop, $stack->pop); $stack->push(bool2num($a && $b)) } },
		'||'  => sub { if ($stack->has(2)) { my ($a,$b) = ($stack->pop, $stack->pop); $stack->push(bool2num($a || $b)) } },
		# unary
		'++'  => sub { if ($stack->has(1)) { $stack->push($stack->pop + 1) } },
		'--'  => sub { if ($stack->has(1)) { $stack->push($stack->pop - 1) } },
		# functions
		pop   => sub { if ($stack->has(1)) { $stack->pop } },
		peek  => sub { if ($stack->has(1)) { print q[peek> ]. $stack->get(1) .qq[\n] } },
		stack => sub { print q[stack#> ]. $stack->size .qq[\n] },
		dump  => sub { my $n = $stack->size; foreach my $s (reverse $stack->dump) { $n--; print qq[stack$n> $s\n]; } },
		flush => sub { $stack->flush }, # toss it all
		empty => sub { $stack->push($stack->empty) },
		load  => sub { $register->load },
		lall  => sub { $register->load while $stack->size > 0 },
		mdmp  => sub { $register->dump },
		step  => sub { $register->step },
		noop  => undef
	);
	%help =
	(
		'=='  => q[Test equality, push result to stack],
		'!='  => q[Test inequality, push result to stack],
		'<'   => q[Test less-than, push result to stack],
		'>'   => q[Test greater-than, push result to stack],
		'<='  => q[Test less-than-equals, push result to stack],
		'>='  => q[Test greater-than-equals, push result to stack],
		'?'   => q[Pop three stack items, push (FIRST ? SECOND : THIRD) to stack],
		'+'   => q[Pop two stack items, add them, push result to stack],
		'/'   => q[Pop two stack items, divide them, push the result to stack],
		'*'   => q[Pop two stack items, multiply them, push the result to stack],
		'-'   => q[Pop two stack items, subtract them, push the result to stack],
		'%'   => q[Pop two stack items, compute FIRST % SECOND, push the result to the stack],
		'**'  => q[Pop two stack items, exponentiate them, push the result to the stack],
		'^'   => q[Pop two stack items, bitwise-xor them, push the result to the stack],
		'&'   => q[Pop two stack items, bitwise-and them, push the result to the stack],
		'|'   => q[Pop two stack items, bitwise-or them, push the result to the stack],
		'<<'  => q[Pop two stack items, bitwise-shift them left, push the result to the stack],
		'>>'  => q[Pop two stack items, bitwise-shift them right, push the result to the stack],
		'&&'  => q[Pop two stack items, logical-and them, push the result to the stack],
		'||'  => q[Pop two stack items, locical-or them, push the result to the stack],
		'++'  => q[Increment value on top of the stack],
		'--'  => q[Decrement value on top of the stack],
		pop   => q[Pop the stack],
		peek  => q[Peek at the top of the stack],
		stack => q[Show stack information],
		dump  => q[Dump the stack],
		flush => q[Flush the stack completely],
		empty => q[Test if the stack is empty, push the result to stack],
		load  => q[Pop the stack into the next memory location],
		lall  => q[Pop the stack into the next memory location until empty],
		step  => q[Step the register machine],
		noop  => q[NOOOOOOP]
	);
}

sub execute
{
	$command = shift;

	if ($command =~ /^(?:\+|-)?(?:0[xXbB])?\d+(?:\.\d+)?(?:e\d+)?$/)
	{
		# push numbers onto the stack
		$stack->push(force2num($command));
	}
	elsif (exists($operation{$command}))
	{
		# grab commands if we have them
		$command = $operation{$command};
	}
	elsif ($command =~ /^help:(.+)/i)
	{
		$command = lc($1);

		if ($command eq q[list])
		{
			print q[list> ]. join(q[, ], keys(%operation)) .qq[\n];
		}
		elsif (exists($help{$command}))
		{
			print qq[help[$command]> $help{$command}\n];
		}
		else
		{
			warn RPN::Error->INPUT_UNKNOWN_CMD;
		}
	}
	elsif ($command =~ /^help/i)
	{
		print qq[help>\n];
		print qq[\t   Get a listing: help:list\n];
		print qq[\tGet command help: help:<command>\n];
	}
	else
	{
		warn RPN::Error->INPUT_UNKNOWN_CMD;
	}

	$command->(@_) if (ref($command));

	undef($command);
}



  ######
  #   RPN::Stack
   #    A singular stack...What fun is that?

package RPN::Stack;

use strict;

sub init  { my @s = (); return (bless \@s) }
sub has   { my $e = shift->size >= shift; warn RPN::Error->STACK_EMPTY unless $e; return ($e) }
sub dump  { @{shift()} }
sub flush { @{shift()} = () }
sub size  { int(@{shift()}) }
sub empty { not(shift->size) }
sub push  { push(@{shift()}, @_) }
sub pop   { pop(@{shift()}) }
sub set   { shift->[0 - shift] = shift } # reverse indexed
sub get   { shift->[0 - shift] } # ditto
sub top   { shift->get(1) }



  ######
  #   RPN::Stack::Frame
   #    Manages the stacks (even for the calculator).
   #    It will never drop the final frame which is
   #    the RPN calculator's stack.

package RPN::Stack::Frame;

use strict;

sub init  { my @f = (RPN::Stack->init); return (bless \@f) }
sub flush { my $f = shift; $f->pop while ($f->size > 1) }
sub pop   { my $f = shift; pop(@{$f}) if ($f->size > 1) }
sub push  { my $f = shift; push(@{$f}, RPN::Stack->init); return ($f->get) }
sub size  { int(@{shift()}) }
sub get   { shift->[0 - shift] }
sub top   { shift->get(1) }



  ######
  #   RPN::Register
   #    The control unit! Manages memory, registers,
   #    and probably some other important stuff...

package RPN::Register;

use strict;

# super helpers
sub hexify($)  { sprintf(q[0x%016X], shift) }
sub num2reg($) { sprintf(q[R%d], shift) } # note R0 is a special register

# just helpers
sub HIGH32($) { (0xFFFFFFFF00000000 & shift) >> 32 }
sub LOW32($)  { 0x00000000FFFFFFFF & shift }
sub HIGH16($) { (0xFFFF0000 & shift) >> 16 }
sub LOW16($)  { 0x0000FFFF & shift }
sub HIGH8($)  { 0xFF00 & shift }
sub LOW8($)   { (0x00FF & shift) >> 8 }

my %opcode; # static crap

sub init
{
	my %self =
	(
		register => {},
		memory   => {},
		frame    => RPN::Stack::Frame->init
	);

	$self{register}->{INSR} = hexify(0);
	$self{register}->{PC} = RPN::Constant->DEF_MEM_BEGIN;

	return (bless \%self);
}

# fetchers
sub register    { shift->{register} }
sub memory      { shift->{memory} }
sub stack       { shift->frame->top }
sub frame       { shift->{frame} }
# read only shaz
sub instruction { hexify(shift->register->{INSR}) }
sub command     { hexify(LOW32(shift->instruction)) }
sub data        { hexify(HIGH32(shift->instruction)) }
sub counter     { hexify(shift->register->{PC}) }
sub next_pc     { hexify(shift->register->{PC}++) }
# more fun things
sub load        { my $s = shift; $s->memory->{$s->next_pc} = $s->stack->pop }
sub dump
{
	my $s = shift;
	for (my $i = RPN::Constant->DEF_MEM_BEGIN; $i < $s->counter; $i++)
	{
		print q[MEM(]. hexify($i) .q[) => ]. hexify($s->memory->{hexify($i)}) .qq[\n];
	}
}


# setup the static crap
sub prime
{
	%opcode =
	(
		# low ops (debug, testing, etc)
		hexify(0x00) => sub { }, # noop
		hexify(0x01) => sub { print q[REG(INSR) : ]. shift->instruction .qq[\n] }, # what did I just send you?
		hexify(0x02) => sub { print q[REG(PC)   : ]. shift->counter .qq[\n] },
		hexify(0x03) => sub { print q[REG(CMD)  : ]. shift->command .qq[\n] }, # should always return 0x00000003
		hexify(0x04) => sub { print q[REG(DATA) : ]. shift->data .qq[\n] },
		# stack ops
		hexify(0x10) => sub { my $s = shift; $s->memory->{hexify($s->data)} = $s->stack->pop }, # sts
		hexify(0x11) => sub { my $s = shift; $s->stack->push($s->memory->{hexify($s->data)}) }, # lds
		hexify(0x12) => sub { my $s = shift; $s->memory->{hexify($s->register->{PC}++)} = $s->stack->pop }, # stsi
		hexify(0x13) => sub { my $s = shift; $s->stack->push($s->memory->{hexify($s->register->{PC}++)}) }, # ldsi
		hexify(0x14) => sub { my $s = shift; $s->memory->{hexify($s->register->{PC}--)} = $s->stack->pop }, # stsd
		hexify(0x15) => sub { my $s = shift; $s->stack->push($s->memory->{hexify($s->register->{PC}--)}) }, # ldsd
		# register ops
		hexify(0x20) => sub { my $s = shift; $s->memory->{hexify($s->data)} = $s->register->{R0} }, # str
		hexify(0x21) => sub { my $s = shift; $s->register->{R0} = $s->memory->{hexify($s->data)} }, # ldr
		# b-b-b-b-b-b-branch
		hexify(0x30) => sub { my $s = shift; $s->register->{PC} = $s->data }, # br
		hexify(0x31) => sub { my $s = shift; }, #jsr => stack frame push, set recall, branch, stack frame pop
	);
}



  ######
  #   RPN::Constant
   #    No more scary constants...Well some.

package RPN::Constant;

use strict;

sub DEF_STACK_BEGIN()
{ 0 }
sub DEF_MEM_BEGIN()
{ 0 }



  ######
  #   RPN::Error
   #    A collection of error messages, pure poetry.

package RPN::Error;

use strict;

sub STACK_EMPTY()
{ q[Stack is empty, what are you doing] }
sub INPUT_UNKNOWN_CMD()
{ q[Unknown operation found while parsing input, what are you doing] }
sub POSSIBLE_BUFFER_OVERFLOW()
{ q[Hit unintialized memory, what are you doing] }



__END__
